spring:
  application:
    name: helloworld

---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://root:@localhost:3306/hello_world

---
spring:
  profiles: production
  datasource:
    url: ${JAWSDB_URL}

---
spring:
  profiles: aws-production
  datasource:
    url: jdbc:mysql://admin:monkey55@database-1.cyyrsyljuwjo.us-west-1.rds.amazonaws.com:3306/hello_world


