spring:
  datasource:
    url: jdbc:mysql://jp9r93j6dhyawgub:ayjuiz72atbtkbn1@w1h4cr5sb73o944p.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/zp8kambguwsfizay
#   url: jdbc:mysql://root:@localhost:3306/hello_world
